--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29.12.2016 11:35:02
-- Server version: 5.5.8-log
-- Client version: 4.1
--


--
-- Definition for database test
--
DROP DATABASE IF EXISTS test;
CREATE DATABASE IF NOT EXISTS test
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE test;

--
-- Definition for table reservation
--
CREATE TABLE IF NOT EXISTS reservation (
  FullName VARCHAR(255) DEFAULT NULL,
  Address VARCHAR(255) DEFAULT NULL,
  Age VARCHAR(255) DEFAULT NULL,
  Profession VARCHAR(255) DEFAULT NULL,
  rStatus VARCHAR(255) DEFAULT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table reservation
--
INSERT INTO reservation VALUES
('Name1', 'Addre', '32', 'proff', 'Non-Resident');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;